name: Bootstrap issues
on: ["create"]
if: github.event.ref == github.event.master_branch
permissions:
    issues: write 
jobs:
  create-issues:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jayalfredprufrock/create-issues-action@v1.2.1
